"""empty message

Revision ID: 0d8ee6a7d471
Revises: 1c8234f7f638
Create Date: 2018-08-13 18:35:23.316387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8ee6a7d471'
down_revision = '1c8234f7f638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'number_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('number_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
