"""empty message

Revision ID: 0ea2e5b2f7cf
Revises: aa7e960c6d2d
Create Date: 2018-08-14 11:15:36.910880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea2e5b2f7cf'
down_revision = 'aa7e960c6d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'message')
    op.drop_column('campaign', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
