"""empty message

Revision ID: 1c8234f7f638
Revises: 751036b88e23
Create Date: 2018-08-13 18:33:50.724559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8234f7f638'
down_revision = '751036b88e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('number_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'number_status')
    # ### end Alembic commands ###
