"""empty message

Revision ID: 69f164f1a799
Revises: 4fbdfef48594
Create Date: 2018-08-13 13:57:04.653770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f164f1a799'
down_revision = '4fbdfef48594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'status')
    # ### end Alembic commands ###
