"""empty message

Revision ID: 751036b88e23
Revises: 69f164f1a799
Create Date: 2018-08-13 17:50:58.744746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751036b88e23'
down_revision = '69f164f1a799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('schedule', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'schedule')
    # ### end Alembic commands ###
