"""empty message

Revision ID: 89dc24db0e79
Revises: 0d8ee6a7d471
Create Date: 2018-08-13 18:35:34.886852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dc24db0e79'
down_revision = '0d8ee6a7d471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('number_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'number_status')
    # ### end Alembic commands ###
