"""empty message

Revision ID: a17619886ea0
Revises: 2e2fe1b6091e
Create Date: 2018-08-16 15:43:34.353985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17619886ea0'
down_revision = '2e2fe1b6091e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('status_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'status_type')
    # ### end Alembic commands ###
