"""empty message

Revision ID: aa7e960c6d2d
Revises: 93869ad65a84
Create Date: 2018-08-14 11:10:07.200864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7e960c6d2d'
down_revision = '93869ad65a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'number')
    # ### end Alembic commands ###
